### ISSUE TITLE
mcast_rate für Wifi-Mesh

### ISSUE THREAD

**Issue by Sunz3r** [ffggrz/site-ffggrz#10]
Für 802.11s und IBSS gibts eine mindest-Datenrate für Multicast und Broadcast-Pakete. Wenn diese zu hoch ist können schlecht angebundene Knoten nicht mehr erreicht werden, wodurch die TQ sinkt.
Kleinere Werte belegen allerdings mehr AirTime, wodurch weniger Bandbreite möglich ist.

Viele Communitys setzen diese mittlerweile auf 6000, was für 6 MBit/s steht.

**Comment by joerg-d** [comment]
Dann schlage ich vor, das mal auf einer solchen Strecke zu testen. Wenns dann wirklich besser wird, können wir überlegen, ob wir das generell in der site.conf so setzen oder nur eine Konfigurationsempfehlung für Betreiber solcher schlechten Strecken empfehlen.

**Comment by thillux** [comment]
Dieses Issue kann eig. geschlossen werden, da mittlerweile eine mcast_rate von 12 Mbit/s in der site.conf konfiguriert ist.

**Comment by maklein** [comment]
veraltet
