### ISSUE TITLE
Update der Config auf v2020.2

### ISSUE THREAD

**Issue by thillux** [ffggrz/site-ffggrz#19]
Ich habe ein bisschen mit der neuesten Gluon-Version herumgetestet. Folgendes ist mir aufgefallen:

1) haveged wird nicht mehr verwendet und kann daher aus den Paketen entfernt werden
2) mesh_on_lan funktioniert nicht, wenn es im Config-Wizard ausgewählt wird
    Fix war für mich, in /etc/config/firewall mesh_lan als network der wired_mesh Zone zu setzen.
    Problem ist, dass in der Standard-Config die Chain für wired_mesh Input nicht angesprungen wird,
    welche den VXLAN-Destination-Port erlaubt.

(1) kann natürlich lokal in site-ffggrz gefixt werden, dass habe ich auch in meinem Fork (https://github.com/thillux/site-ffggrz) gemacht.
(2) sollte wahrscheinlich in gluon selbst gefixt werden. Reicht es dazu, meinen kleinen Fix als Config-Preset zu setzen oder gehört da mehr dazu? Das überblicke ich gerade nicht sofort, da ich vor zwei Tagen das erste mal auf Freifunk/OpenWRT geschaut habe. Sollte aber eig. nicht weiter schwierig sein.

**Comment by thillux** [comment]
Ich habe ein Issue im gluon Repository für (2) angelegt. https://github.com/freifunk-gluon/gluon/issues/2090

**Comment by thillux** [comment]
freifunk-gluon/gluon#2090 wurde mittlerweile in https://github.com/freifunk-gluon/gluon/pull/2091 gefixt.

**Comment by anoymouserver** [comment]
Thanks, fixed with bcf6193fb1060cb860b142cc62b9f38641c467dc
